title: Wenbin Feng's Homepage
page-top-title: Wenbin Feng
top-section-bg-text: Be what you wanna be
home-subtitle: Wenbin Feng&ensp;|&ensp;Wenbin Feng
copyright-text: '&copy; Wenbin Feng 2023-2025. All Rights Reserved.'
